演習問題1

In [2]:
import pandas as pd

game = pd.read_excel('game.xlsx')
game

    年齢  プレイ時間  配信
0  10代    2.3   0
1  20代    1.8   1
2  10代    3.7   1
3  10代    1.4   0
4  10代    4.5   0
5  20代    2.4   1
6  20代    1.3   1
7  10代    3.2   0
8  20代    2.2   0
9  20代    1.9   0

In [6]:
teens = game[game['年齢'] == '10代']
print("10代の学生のゲームプレイ時間の平均は",teens['プレイ時間'].mean(),"時間です")

10代の学生のゲームプレイ時間の平均は 3.0200000000000005 時間です

In [5]:
twenty = game[game['年齢'] == '20代']
print("20代の学生のゲームプレイ時間の平均は",twenty['プレイ時間'].mean(),"時間です")

20代の学生のゲームプレイ時間の平均は 1.92 時間です

In [8]:
from scipy import stats
stats.ttest_ind(teens['プレイ時間'], twenty['プレイ時間'], equal_var = False)

TtestResult(statistic=1.9242064284886298, pvalue=0.11281344014914552, df=4.957725870378399)

pvalueが0.025より大きいので、10代と20代の学生のゲームプレイ時間には差がないと言える

演習問題2

In [10]:
cross_table = pd.crosstab(game['年齢'], game['配信'])
cross_table

配信   0  1
年齢
10代  4  1
20代  2  3

In [11]:
from scipy import stats
alpha = 0.05  # 有意水準5%
df = 1        # クロス集計表が2行2列なので((2-1)*(2-1)=1)
stats.chi2.ppf(1-alpha, df)

3.841458820694124

In [12]:
stats.chi2_contingency(cross_table, correction=True)

Chi2ContingencyResult(statistic=0.41666666666666663, pvalue=0.5186050164287255, dof=1, expected_freq=array([[3., 2.],
       [3., 2.]]))

理論値が3.841 算出値が0.416

理論値が算出値と比較して大幅に大きいので、配信の有無と年齢は互いに独立した項目であることが分かる。(連関がない)