In [2]:
import pandas as pd

table = pd.read_html("https://ja.wikipedia.org/wiki/%E5%85%83%E7%B4%A0")
table[1]

     日本語表記 元素記号    英語（IUPAC名）         ドイツ語          ラテン語 中国語
0       水素    H      Hydrogen  Wasserstoff   Hydrogenium   氫
1     ヘリウム   He        Helium       Helium        Helium   氦
2     リチウム   Li       Lithium      Lithium       Lithium   鋰
3    ベリリウム   Be     Beryllium    Beryllium     Beryllium   鈹
4      ホウ素    B         Boron          Bor        Borium   硼
5       炭素    C        Carbon  Kohlenstoff     Carbonium   碳
6       窒素    N      Nitrogen   Stickstoff   Nitrogenium   氮
7       酸素    O        Oxygen   Sauerstoff     Oxygenium   氧
8      フッ素    F      Fluorine        Fluor       Fluorum   氟
9    ナトリウム   Na        Sodium      Natrium       Natrium   鈉
10  アルミニウム   Al     Aluminium    Aluminium     Aluminium   鋁
11     ケイ素   Si       Silicon     Silicium      Silicium   硅
12      リン    P    Phosphorus     Phosphor    Phosphorus   磷
13      硫黄    S        Sulfur     Schwefel       Sulphur   硫
14      塩素   Cl      Chlorine        Chlor       Chlorum   氯
15    カリウム    K     Potassium       Kalium        Kalium   鉀
16     チタン   Ti      Titanium        Titan      Titanium   鈦
17     クロム   Cr      Chromium        Chrom      Chromium   鉻
18    マンガン   Mn     Manganese       Mangan      Manganum   錳
19       鉄   Fe          Iron        Eisen        Ferrum   鐵
20       銅   Cu        Copper       Kupfer        Cuprum   銅
21      亜鉛   Zn          Zinc         Zink        Zincum   鋅
22      ヒ素   As       Arsenic        Arsen     Arsenicum   砷
23     セレン   Se      Selenium        Selen      Selenium   硒
24      臭素   Br       Bromine         Brom        Bromum   溴
25     ニオブ   Nb       Niobium         Niob       Niobium   鈮
26   モリブデン   Mo    Molybdenum     Molybdän    Molybdenum   鉬
27       銀   Ag        Silver       Silber      Argentum   銀
28      スズ   Sn           Tin         Zinn       Stannum   錫
29   アンチモン   Sb      Antimony      Antimon       Stibium   銻
30     テルル   Te     Tellurium       Tellur     Tellurium   碲
31     ヨウ素    I        Iodine          Iod         Iodum   碘
32    ランタン   La     Lanthanum      Lanthan     Lanthanum   鑭
33  プラセオジム   Pr  Praseodymium    Praseodym  Praseodymium   鐠
34    ネオジム   Nd     Neodymium       Neodym     Neodymium   釹
35    タンタル   Ta      Tantalum       Tantal      Tantalum   鉭
36      白金   Pt      Platinum       Platin      Platinum   鉑
37       金   Au          Gold         Gold         Aurum   金
38      水銀   Hg       Mercury  Quecksilber  Hydrargentum   汞
39       鉛   Pb          Lead         Blei       Plumbum   鉛
40     ウラン    U       Uranium         Uran       Uranium   鈾

In [3]:
table[1].to_excel("elements.xlsx")

In [9]:
table = pd.read_html("https://altema.jp/pokemonsv/syuzokuchi_list")
table[2]

        ポケモン    H    A    B    C    D    S   合計
0       ニャオハ   40   61   54   45   45   65  310
1      ニャローテ   61   80   63   60   63   83  410
2     マスカーニャ   76  110   70   81   70  123  530
3       ホゲータ   67   45   59   63   40   36  310
4      アチゲータ   81   55   78   90   68   49  421
..       ...  ...  ...  ...  ...  ...  ...  ...
828     ガチグマ  130  140  105   45   80   50  550
829   オオニューラ   80  130   60   40   80  120  510
830    ラブトロス   74  115   70  135   80  106  580
831  霊獣ラブトロス   74  115  110  135  100   46  580
832    モモワロウ   88   88  160   88   88   88  600

[833 rows x 8 columns]

In [10]:
table[2].to_excel("pokemon.xlsx")